### ISSUE TITLE
本地不能安装项目模板

### ISSUE THREAD

**Issue by xuhuidashi** [WangJunZzz/abp-vnext-pro#1]
在content文件夹下执行：dotnet new -i .\content 
提示：Error: Couldn't find item to install: ".\content".

![image](https://user-images.githubusercontent.com/47109067/109815786-fee91d80-7c6a-11eb-93a3-0fad2d250dc4.png)

**Comment by Bingo0007** [comment]
退到上一级目录执行

**Comment by xuhuidashi** [comment]
可以了，感谢。
