### ISSUE TITLE
调试模式下能正常显示本地化文本，部署后，只能显示数据表中的文本，json 文件资源中的文本的无法显示

### ISSUE THREAD

**Issue by Evil2017** [WangJunZzz/abp-vnext-pro#104]

**Comment by WangJunZzz** [comment]
所有的都不能显示？描述详细一点

**Comment by Evil2017** [comment]
很可能是项目属性文件 配置的问题，我还原到初始状态才正常。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月26日(星期三) 下午3:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WangJunZzz/abp-vnext-pro] 调试模式下能正常显示本地化文本，部署后，只能显示数据表中的文本，json 文件资源中的文本的无法显示 (Issue #104)





 
Closed #104 as completed.
