### ISSUE TITLE
用cli生成后出现解译错误

### ISSUE THREAD

**Issue by easonechan** [WangJunZzz/abp-vnext-pro#107]
版本为 7.3.3.4

有些类文件没获取到最新源码库？出现循环类型依赖项。

比如最新源码中名称为AbpProExceptionFilter.cs，而用cli生成的类文件还是AbpExceptionFilter.cs。

**Comment by WangJunZzz** [comment]
cli 的命令是什么

**Comment by easonechan** [comment]
> cli 的命令是什么

lion.abp new -t pro -c ESoft -p Abp

**Comment by WangJunZzz** [comment]
你的-p 参数 叫做Abp生产的代码和原来的abp自带的类相同，你可以手动修改这个类，或者改个名字

**Comment by easonechan** [comment]
> 你的-p 参数 叫做Abp生产的代码和原来的abp自带的类相同，你可以手动修改这个类，或者改个名字

好，多谢
