### ISSUE TITLE
代码生成的怎么下载？或者模板生成？

### ISSUE THREAD

**Issue by He-Wu** [WangJunZzz/abp-vnext-pro#111]

**Comment by WangJunZzz** [comment]
安装 cli dotnet tool install Lion.AbpPro.Cli -g

**Comment by He-Wu** [comment]
我是说的代码生成模块suite，目前只能在线预览无法集成到自己的项目

**Comment by He-Wu** [comment]
@WangJunZzz

**Comment by WangJunZzz** [comment]
可以把生成的代码下载下来 复制过去

**Comment by He-Wu** [comment]
> 可以把生成的代码下载下来 复制过去

意思是只能用你的预览地址生成？

**Comment by WangJunZzz** [comment]
暂时没有，你可以把代码生成器下载下来修改
