### ISSUE TITLE
求教一个问题，代码VS运行没问题，当发布后能运行，但是无法访问。

### ISSUE THREAD

**Issue by Jsmin** [WangJunZzz/abp-vnext-pro#113]
项目可以运行，也不报错。
![image](https://github.com/WangJunZzz/abp-vnext-pro/assets/7332324/25d096e6-7517-4af5-b373-671e69bc2319)
只有运行了一个这个

**Comment by WangJunZzz** [comment]
错误日志贴一下

**Comment by Jsmin** [comment]
> 错误日志贴一下

就我发的这个，没有报任何的错误日志，有错误日志就好了
![image](https://github.com/WangJunZzz/abp-vnext-pro/assets/7332324/e17056a8-4b23-4c67-b5cf-a84530f36be0)

**Comment by WangJunZzz** [comment]
加qq群，我远程看看

**Comment by Jsmin** [comment]
> 加qq群，我远程看看

好，我加了
