### ISSUE TITLE
还原Nuget失败

### ISSUE THREAD

**Issue by 37c2** [WangJunZzz/abp-vnext-pro#114]
![image](https://github.com/WangJunZzz/abp-vnext-pro/assets/49016888/83700aed-49e2-4e00-ab5b-fe9ae535a9d5)

**Comment by WangJunZzz** [comment]
在Directory.Build.targets加上 <Import Project="Directory.Build.Lion.targets"/>
![556d568908126f0e9663ec32b873a4c6](https://github.com/WangJunZzz/abp-vnext-pro/assets/25657426/82b3ea79-1871-47f6-970c-7eebc73a86e6)
或者重新下载项目
