### ISSUE TITLE
前端进入审计日志和登录日志菜单报错

### ISSUE THREAD

**Issue by duanwenhao** [WangJunZzz/abp-vnext-pro#117]
![image](https://github.com/WangJunZzz/abp-vnext-pro/assets/27075442/2fbbe2c6-60db-4226-a5ed-ec539c282f24)
进出后加载不出数据，出错后不能再切换回其他的菜单

**Comment by WangJunZzz** [comment]
什么版本，可以复现吗？

**Comment by WangJunZzz** [comment]
什么版本，可以复现吗？

**Comment by duanwenhao** [comment]
用最新cli拉下来的8.0版，我在群里也反馈过这个问题，应该是那个时间段查询条件的问题，去掉那个时间段控件就没这个错误了

**Comment by WangJunZzz** [comment]
没有复现
