### ISSUE TITLE
请问一下我用pro.simple模板生成的项目如何为用户新增字段？

### ISSUE THREAD

**Issue by Jsmin** [WangJunZzz/abp-vnext-pro#120]
现在项目需要 我要为用户新增字段属性，但是现在项目用户管理是封装好了的，请问怎么样用户新增字段？

**Comment by WangJunZzz** [comment]
abp 官方提供了扩展字段，或者借用userclaims

**Comment by Jsmin** [comment]
> abp 官方提供了扩展字段，或者借用userclaims

好的我试一下
