### ISSUE TITLE
我想通过ServiceProvider获取IRepository<DataDictionaryDetail, Guid>，求教下有办法获取吗？

### ISSUE THREAD

**Issue by Jsmin** [WangJunZzz/abp-vnext-pro#122]
` using(var scope = GlobalServiceScopeFactory.Instance.CreateScope())
 {
     var appService = scope.ServiceProvider.GetRequiredService<IRepository<DataDictionaryDetail, Guid>>();
     var item = AsyncHelper.RunSync(() => appService.FirstOrDefaultAsync(x => x.Id == dicId));

     return item?.DisplayText;
 }`

 Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Volo.Abp.Domain.Repositories.IRepository`2[[Lion.AbpPro.DataDictionaryManagement.DataDictionaries.Aggregates.DataDictionaryDetail, Lion.AbpPro.DataDictionaryManagement.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Guid, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

**Comment by WangJunZzz** [comment]
var item = AsyncHelper.RunSync(() => await appService.FirstOrDefaultAsync(x => x.Id == dicId));

**Comment by Jsmin** [comment]
> var item = AsyncHelper.RunSync(() => await appService.FirstOrDefaultAsync(x => x.Id == dicId));

不是这个问题，还没走到这一步，在var appService = scope.ServiceProvider.GetRequiredService<IRepository<DataDictionaryDetail, Guid>>();这一步就已经报错了，而且我想在服务中注入使用IDataDictionaryManager
`private readonly BaseProjectManager _baseProjectManager;
private readonly IDataDictionaryManager _dataDictionaryManager;

public BaseProjectAppService(
    BaseProjectManager baseProjectManager,
    IDataDictionaryManager dataDictionaryManager)
{
    _baseProjectManager = baseProjectManager;
    _dataDictionaryManager = dataDictionaryManager;
}
 var testResult = await _dataDictionaryManager.FindByIdAsync(Guid.Parse("3a1056bc-0227-9e74-6770-d8574c39a303"));
`
这个testResult是null，无法获取到数据。

**Comment by WangJunZzz** [comment]
数据库有这个吗

**Comment by WangJunZzz** [comment]
传递的id是字典id，不是字典明细id

**Comment by Jsmin** [comment]
> 传递的id是字典id，不是字典明细id
哦哦对，这个我传错了！通过字典id可以获取字典明细，晕了。


> ` using(var scope = GlobalServiceScopeFactory.Instance.CreateScope()) { var appService = scope.ServiceProvider.GetRequiredService<IRepository<DataDictionaryDetail, Guid>>(); var item = AsyncHelper.RunSync(() => appService.FirstOrDefaultAsync(x => x.Id == dicId));
> 
> ```
>  return item?.DisplayText;
> ```
> 
> }`
> 
> Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Volo.Abp.Domain.Repositories.IRepository`2[[Lion.AbpPro.DataDictionaryManagement.DataDictionaries.Aggregates.DataDictionaryDetail, Lion.AbpPro.DataDictionaryManagement.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Guid, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.

这个有办法解决吗？或者能不能在IDataDictionaryManager中添加一个通过字典明细id获取字典明细的方法。

**Comment by WangJunZzz** [comment]
你扩展一下接口

**Comment by WangJunZzz** [comment]
我后面也可以添加上去

**Comment by Jsmin** [comment]
> 你扩展一下接口

好的，那我扩展一下吧。
