### ISSUE TITLE
Window10用lion.abp创建项目，编译失败的问题

### ISSUE THREAD

**Issue by zh-zhang-127** [WangJunZzz/abp-vnext-pro#129]
E:\demo>lion.abp new -t pro.simplify -c Yiparts -p AbpProDemo
[13:55:56 INF] ABP Pro CLI (https://https://doc.cncore.club/)
[13:55:56 INF] 请输入 lion.abp help 查看所有命令
[13:55:59 INF] Lion AbpPro Version:8.1.1.1
[13:55:59 INF] 模板生成中......
[13:56:06 INF] OutputFolder:E:\demo\Yiparts.AbpProDemo

E:\demo>cd Yiparts.AbpProDemo

E:\demo\Yiparts.AbpProDemo>cd aspnet-core

E:\demo\Yiparts.AbpProDemo\aspnet-core>dotnet restore
  Determining projects to restore...
E:\demo\Yiparts.AbpProDemo\aspnet-core\test\Yiparts.AbpProDemo.TestBase\Yiparts.AbpProDemo.TestBase.csproj : error NU1605: 错误形式的警告: 检测到包降级: Volo.Abp.Authorization 从 8.1.1 降级到 8.0.4。直接从项目引用包以选择不同版本。  [E:\demo\Yiparts.AbpProDemo\aspnet-core\Yiparts.AbpProDemo.sln]
E:\demo\Yiparts.AbpProDemo\aspnet-core\test\Yiparts.AbpProDemo.TestBase\Yiparts.AbpProDemo.TestBase.csproj : error NU1605:  Yiparts.AbpProDemo.TestBase -> Yiparts.AbpProDemo.Domain -> Lion.AbpPro.BasicManagement.Domain 8.1.1.1 -> Volo.Abp.PermissionManagement.Domain.Identity 8.1.1 -> Volo.Abp.PermissionManagement.Domain 8.1.1 -> Volo.Abp.Authorization (>= 8.1.1)  [E:\demo\Yiparts.AbpProDemo\aspnet-core\Yiparts.AbpProDemo.sln]
E:\demo\Yiparts.AbpProDemo\aspnet-core\test\Yiparts.AbpProDemo.TestBase\Yiparts.AbpProDemo.TestBase.csproj : error NU1605:  Yiparts.AbpProDemo.TestBase -> Volo.Abp.Authorization (>= 8.0.4) [E:\demo\Yiparts.AbpProDemo\aspnet-core\Yiparts.AbpProDemo.sln]
E:\demo\Yiparts.AbpProDemo\aspnet-core\test\Yiparts.AbpProDemo.TestBase\Yiparts.AbpProDemo.TestBase.csproj : error NU1605: 错误形式的警告: 检测到包降级: Volo.Abp.Autofac 从 8.1.1 降级到 8.0.4。直接从项目引用包以选择不同版本。  [E:\demo\Yiparts.AbpProDemo\aspnet-core\Yiparts.AbpProDemo.sln]
E:\demo\Yiparts.AbpProDemo\aspnet-core\test\Yiparts.AbpProDemo.TestBase\Yiparts.AbpProDemo.TestBase.csproj : error NU1605:  Yiparts.AbpProDemo.TestBase -> Yiparts.AbpProDemo.Domain -> Yiparts.AbpProDemo.Domain.Shared -> Lion.AbpPro.Core 8.1.1.1 -> Lion.AbpPro.Localization 8.1.1.1 -> Volo.Abp.Autofac (>= 8.1.1)  [E:\demo\Yiparts.AbpProDemo\aspnet-core\Yiparts.AbpProDemo.sln]
……
  未能还原 E:\demo\Yiparts.AbpProDemo\aspnet-core\host\Yiparts.AbpProDemo.HttpApi.Host\Yiparts.AbpProDemo.HttpApi.Host.csproj (用时 5.32 秒)。
  12 个项目(共 15 个)是最新的，无法还原。

**Comment by zh-zhang-127** [comment]
补充下我的dotnet环境，装了 .Net 7.0、8.0
E:\demo\Yiparts.AbpProDemo\aspnet-core>dotnet --list-sdks
7.0.410 [C:\Program Files\dotnet\sdk]
8.0.303 [C:\Program Files\dotnet\sdk]

**Comment by WangJunZzz** [comment]
使用lion.abp new -t pro -c Yiparts -p AbpProDemo
