### ISSUE TITLE
The Libs folder under the wwwroot/libs directory is empty!

### ISSUE THREAD

**Issue by kuaidaoyanglang** [WangJunZzz/abp-vnext-pro#133]
I get this issue when I try run the Tomorrow.GPTPlus.HttpApi.Host, do you have any idea about this?
![image](https://github.com/user-attachments/assets/e4a21455-d9f9-4236-a2ee-f9a376862b25)

**Comment by WangJunZzz** [comment]
你使用的是我的项目，还是官方abp的？

**Comment by beginner5121** [comment]
> 你使用的是我的项目，还是官方abp的？

我的也是这样，用你的项目

**Comment by WangJunZzz** [comment]
升级abp8.3.0 导致，已经修复，

**Comment by kuaidaoyanglang** [comment]
​ 您好，你发的邮件已经收到，我会尽快处理，谢谢！！
