### ISSUE TITLE
前端monorepo化

### ISSUE THREAD

**Issue by tky753** [WangJunZzz/abp-vnext-pro#15]
vben 2.8 包管理工具改用pnpm了。
pnpm实现monorepo有奇效，因为可以通过软硬链接来连接不同项目。
可以以此为契机，把不同模块的界面 monorepo化。

------

下一步可以考虑用 [vite-plugin-federation](https://github.com/originjs/vite-plugin-federation/tree/main) 实现微前端

**Comment by WangJunZzz** [comment]
好的，会逐步了解。
