### ISSUE TITLE
跑不起来，windows 10系统

### ISSUE THREAD

**Issue by ThreeLambs** [WangJunZzz/abp-vnext-pro#18]
一开始报错路径长度超过260个字符，按教程 https://blog.csdn.net/weixin_41805017/article/details/109526885 去掉限制后，还是跑不起来，nuget包都还原了，没有感叹号。 

1>------ 已启动生成: 项目: CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared, 配置: Debug Any CPU ------
2>------ 已启动生成: 项目: CompanyName.ProjectName.NotificationManagement.EntityFrameworkCore, 配置: Debug Any CPU ------
1>CSC : error CS2001: 未能找到源文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared\obj\Debug\net5.0\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared.GeneratedMSBuildEditorConfig.editorconfig”。
1>已完成生成项目“CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared.csproj”的操作 - 失败。
3>------ 已启动生成: 项目: CompanyName.ProjectName.DataDictionaryManagement.Domain, 配置: Debug Any CPU ------
4>------ 已启动生成: 项目: CompanyName.ProjectName.DataDictionaryManagement.Application.Contracts, 配置: Debug Any CPU ------
3>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared.dll”
3>已完成生成项目“CompanyName.ProjectName.DataDictionaryManagement.Domain.csproj”的操作 - 失败。
5>------ 已启动生成: 项目: CompanyName.ProjectName.DataDictionaryManagement.EntityFrameworkCore, 配置: Debug Any CPU ------
6>------ 已启动生成: 项目: CompanyName.ProjectName.Domain, 配置: Debug Any CPU ------
2>CSC : error CS2001: 未能找到源文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\NotificationManagement\src\CompanyName.ProjectName.NotificationManagement.EntityFrameworkCore\obj\Debug\net5.0\CompanyName.ProjectName.NotificationManagement.EntityFrameworkCore.GeneratedMSBuildEditorConfig.editorconfig”。
2>已完成生成项目“CompanyName.ProjectName.NotificationManagement.EntityFrameworkCore.csproj”的操作 - 失败。
6>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Domain\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Domain.dll”
6>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared.dll”
6>已完成生成项目“CompanyName.ProjectName.Domain.csproj”的操作 - 失败。
4>CSC : error CS2001: 未能找到源文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Application.Contracts\obj\Debug\net5.0\CompanyName.ProjectName.DataDictionaryManagement.Application.Contracts.GeneratedMSBuildEditorConfig.editorconfig”。
4>已完成生成项目“CompanyName.ProjectName.DataDictionaryManagement.Application.Contracts.csproj”的操作 - 失败。
7>------ 已启动生成: 项目: CompanyName.ProjectName.Application.Contracts, 配置: Debug Any CPU ------
7>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Application.Contracts\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Application.Contracts.dll”
7>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared.dll”
7>已完成生成项目“CompanyName.ProjectName.Application.Contracts.csproj”的操作 - 失败。
5>CSC : error CS2001: 未能找到源文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.EntityFrameworkCore\obj\Debug\net5.0\CompanyName.ProjectName.DataDictionaryManagement.EntityFrameworkCore.GeneratedMSBuildEditorConfig.editorconfig”。
5>已完成生成项目“CompanyName.ProjectName.DataDictionaryManagement.EntityFrameworkCore.csproj”的操作 - 失败。
8>------ 已启动生成: 项目: CompanyName.ProjectName.EntityFrameworkCore, 配置: Debug Any CPU ------
8>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Domain\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Domain.dll”
8>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared.dll”
8>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.EntityFrameworkCore\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.EntityFrameworkCore.dll”
8>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\services\src\CompanyName.ProjectName.Domain\bin\Debug\net5.0\ref\CompanyName.ProjectName.Domain.dll”
8>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\NotificationManagement\src\CompanyName.ProjectName.NotificationManagement.EntityFrameworkCore\bin\Debug\net5.0\ref\CompanyName.ProjectName.NotificationManagement.EntityFrameworkCore.dll”
8>已完成生成项目“CompanyName.ProjectName.EntityFrameworkCore.csproj”的操作 - 失败。
9>------ 已启动生成: 项目: CompanyName.ProjectName.DbMigrator, 配置: Debug Any CPU ------
9>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\services\src\CompanyName.ProjectName.Application.Contracts\bin\Debug\net5.0\ref\CompanyName.ProjectName.Application.Contracts.dll”
9>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Application.Contracts\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Application.Contracts.dll”
9>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Domain\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Domain.dll”
9>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.Domain.Shared.dll”
9>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\DataDictionaryManagement\src\CompanyName.ProjectName.DataDictionaryManagement.EntityFrameworkCore\bin\Debug\net5.0\ref\CompanyName.ProjectName.DataDictionaryManagement.EntityFrameworkCore.dll”
9>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\services\src\CompanyName.ProjectName.Domain\bin\Debug\net5.0\ref\CompanyName.ProjectName.Domain.dll”
9>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\services\src\CompanyName.ProjectName.EntityFrameworkCore\bin\Debug\net5.0\ref\CompanyName.ProjectName.EntityFrameworkCore.dll”
9>CSC : error CS0006: 未能找到元数据文件“D:\001.Test\abp-vnext-pro-main\aspnet-core\modules\NotificationManagement\src\CompanyName.ProjectName.NotificationManagement.EntityFrameworkCore\bin\Debug\net5.0\ref\CompanyName.ProjectName.NotificationManagement.EntityFrameworkCore.dll”
9>已完成生成项目“CompanyName.ProjectName.DbMigrator.csproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 9 个，最新 4 个，跳过 0 个 ==========

**Comment by WangJunZzz** [comment]
https://github.com/WangJunZzz/abp-vnext-pro/issues/7

**Comment by WangJunZzz** [comment]
https://github.com/WangJunZzz/abp-vnext-pro/issues/7 参考这个
