### ISSUE TITLE
yarn

### ISSUE THREAD

**Issue by ThreeLambs** [WangJunZzz/abp-vnext-pro#19]
...
[5/6] Building fresh packages...
[7/13] ⡀ mozjpeg
[6/13] ⡀ jpegtran-bin
[8/13] ⢀ optipng-bin
[9/13] ⢀ pngquant-bin
error D:\001.Test\abp-vnext-pro-main\vben271\node_modules\gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: D:\001.Test\abp-vnext-pro-main\vben271\node_modules\gifsicle
Output:
Response code 404 (Not Found)
gifsicle pre-build test failed
compiling from source
Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by WangJunZzz** [comment]
node 版本是多少

**Comment by WangJunZzz** [comment]
修改nmp 镜像源
npm config set registry https://registry.npm.taobao.org
重写yarn 或者 npm install
