### ISSUE TITLE
建议项目名称改支持名词xxx.xxx

### ISSUE THREAD

**Issue by jifeilong9** [WangJunZzz/abp-vnext-pro#2]
目前大部分人喜欢xxx.xxx，建议修改

**Comment by WangJunZzz** [comment]
下个版本尽量完善。

**Comment by WangJunZzz** [comment]
已经支持二级项目生成，代码生成器仓库地址：https://github.com/WangJunZzz/abp-vnext-pro-gui
并且abp-vnext-pro已经升级 请查看readme
