### ISSUE TITLE
Uncaught (in promise) Error: Invalid navigation guard

### ISSUE THREAD

**Issue by adeewu** [WangJunZzz/abp-vnext-pro#20]
启动vue项目后，会报`Uncaught (in promise) Error: Invalid navigation guard`错误，刷新就好了

尝试过vben-admin 2.7.1、2.8.0都没有这个问题，尝试用gui项目直接新建一个也能重现这个情况，排查好久没有找到原因为什么这个项目会出这个问题

重现步骤：
- yarn install
- yarn serve
- 打开浏览器，提前打开开发者调试工具，输入打开：`http://localhost:4200/`
- 开发者调试工具控制台报错提示`Uncaught (in promise) Error: Invalid navigation guard`

![image](https://user-images.githubusercontent.com/5095500/144694192-2923a783-b59f-4724-9082-0865c8702595.png)

**Comment by WangJunZzz** [comment]
下载最新的代码，已经解决了。

**Comment by adeewu** [comment]
速度哟，已经可以了
