### ISSUE TITLE
CDN 找不到bootcss样式

### ISSUE THREAD

**Issue by sanmen359** [WangJunZzz/abp-vnext-pro#22]
CDN 找不到bootcss样式，可以换成 https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

**Comment by WangJunZzz** [comment]
问题有详细描述吗?

**Comment by sanmen359** [comment]
![image](https://user-images.githubusercontent.com/4597642/147041126-b9e2a8d6-4cce-405e-80e7-a737c9a5ba81.png)
https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css 找不到资源，样式错误

**Comment by WangJunZzz** [comment]
这个文件我放到本地来
