### ISSUE TITLE
前后端口号不一致导致项目启动错误

### ISSUE THREAD

**Issue by sanmen359** [WangJunZzz/abp-vnext-pro#23]
前后端口号不一致导致项目启动错误会导致启动错误。可以使用如下方法解决：
# docker-compose与后台接口不一致
修改方法：
mysql
- "3306:3306"
redis
- "6379:6379"
rabbitMq
      - "15672:15672"
      - "5672:5672"
# 前端接口与后端接口不一致
修改方法：
修改文件".env.development"
VITE_API_URL= http://localhost:44315
VITE_WEBSOCKE_URL= http://localhost:44315

**Comment by WangJunZzz** [comment]
docker-compose.yml 只是为了演示 
具体还要看各自设置
