### ISSUE TITLE
身份认证中心里的配置在本系统中的作用

### ISSUE THREAD

**Issue by OldKing-lion** [WangJunZzz/abp-vnext-pro#30]
请教一下，因为已经改写了登录，我看所有的token获取都是从登录接口拿到的，那咱们在身份认证中心里配置的资源和认证方式有什么用呢？ 
如果我要做一个系统，系统有后台管理的用户，有webapi，此时一个用户A调用接口，拿到token，如果是同一个授权方式的话，他管理后台在线的账号就会被踢出，因为token已经变了，他需要刷新页面重新登录才能再次使用。如果api接口调用非常频繁，那后台基本上就会登录就退出吧。
我是说身份认证中心添加不同的认证类型，是否可以解决同一个用户可以同时后台登录和调用api呢，还是我理解错了，有其他的方式？

**Comment by OldKing-lion** [comment]
是否同一个商户用不同的客户端配置可以实现同时在线
![image](https://user-images.githubusercontent.com/13028615/153553084-775345bf-4a79-41e6-bd95-74363e2c89af.png)

**Comment by WangJunZzz** [comment]
至于为什么要单独重新写登录接口的原因：
1.id4 我认为只管认证不管授权，她只颁发token，但是abp把角色放进来了，我认为时不合理的，所以重新写了。就比如id4只颁发身份证，她不管你在哪里用。
2. 使用id4可以用来做单点登录，如果你有api提供给其它人用可以通过id4来授权，不通过abp得。

**Comment by WangJunZzz** [comment]
> 是否同一个商户用不同的客户端配置可以实现同时在线 ![image](https://user-images.githubusercontent.com/13028615/153553084-775345bf-4a79-41e6-bd95-74363e2c89af.png)

这个和在线没有关系

**Comment by OldKing-lion** [comment]
> > 是否同一个商户用不同的客户端配置可以实现同时在线 ![image](https://user-images.githubusercontent.com/13028615/153553084-775345bf-4a79-41e6-bd95-74363e2c89af.png)
> 
> 这个和在线没有关系

嗯，了解了。我只是不太懂这个身份认证的配置有什么作用，比如我加了一个，有什么用呢

**Comment by WangJunZzz** [comment]
具体可以查看Outh2协议，如果项目不需要直接把这块直接删除。

**Comment by WangJunZzz** [comment]
这个身份认证就类似你要用qq登录

**Comment by OldKing-lion** [comment]
好的，等我再研究一下。对ids不是很了解，看到有这个管理，但是不知道干什么用，我看接口请求，都没有带这个信息，就请教一下，感谢耐心回答。

**Comment by OldKing-lion** [comment]
> 这个身份认证就类似你要用qq登录
我理解你的思想了。你目前的做法是自己有登录，然后同时可以用Ids登录。

**Comment by WangJunZzz** [comment]
> > 这个身份认证就类似你要用qq登录
> > 我理解你的思想了。你目前的做法是自己有登录，然后同时可以用Ids登录。

是得  如果现在要接入qq登录扩展stslogin接口就好了，把qq信息保存在用户表就可以了
