### ISSUE TITLE
Serilog 不输出日志文件

### ISSUE THREAD

**Issue by wanglq2008** [WangJunZzz/abp-vnext-pro#31]
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File"
    ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Information",
        "Volo.Abp": "Information",
        "Hangfire": "Information",
        "DotNetCore.CAP": "Information",
        "Serilog.AspNetCore": "Information",
        "Microsoft.EntityFrameworkCore": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "Console"
      },
      **{
        "Name": "RollingFile",
        "Args": {
          "pathFormat": "logs/logs-{Date}.txt"
        }
      }**
    ]
  },

使用 RollingFile 不输出日志文件
改为 
{
        "Name": "File",
        "Args": {
          "path": "logs/logs-.txt",
          "rollingInterval": "Day"
        }
      }
就可以输出日志文件了

**Comment by WangJunZzz** [comment]
我刚刚验证了，确实是的。

**Comment by wanglq2008** [comment]
用户导出文件功能的 deleteDictinaryTypeAsync 方法里的  request.Id = Id; 写错了，request.id 应该小写
