### ISSUE TITLE
abp-vnext-pro vs. abp-next-admin

### ISSUE THREAD

**Issue by 12dollar** [WangJunZzz/abp-vnext-pro#33]
How is abp-vnext-pro different from abp-next-admin (https://github.com/colinin/abp-next-admin) ? May be worth combining efforts?

Google translate: 
abp-vnext-pro 與 abp-next-admin (https://github.com/colinin/abp-next-admin) 有何不同？可能值得共同努力？

**Comment by 12dollar** [comment]
I think this would be more beneficial than keeping two projects with the same scope separate. Just wanted to let you know about the other project. Maybe you can get in touch with the other guys doing abp-next-admin. I can also help out in case it's needed.

**Comment by colinin** [comment]
如果需要，我会为此项目提交一些扩展或修复，这个项目很好文档齐全，更适合了解abp与vben

**Comment by WangJunZzz** [comment]
非常感谢，如果有好的想法和建议可以一起共享。
