### ISSUE TITLE
在设置管理中去掉密码必须包含大写字母与特殊符号后，ChangePasswordAsync依然提示必须包含大写字母与特殊符号

### ISSUE THREAD

**Issue by sxbjy** [WangJunZzz/abp-vnext-pro#34]
在设置管理中去掉密码必须包含大写字母与特殊符号后，ChangePasswordAsync依然提示必须包含大写字母与特殊符号。
但是在用户管理界面添加用户时填写的用户密码无需包含大写字母与特殊符号。

**Comment by WangJunZzz** [comment]
已修改 
https://github.com/WangJunZzz/abp-vnext-pro/commit/2aaab6710518008b59d86ab8e0fcca8e1881710c

**Comment by sxbjy** [comment]
谢谢
