### ISSUE TITLE
看默认配置是mysql，怎么切换到ms sql

### ISSUE THREAD

**Issue by luchaoshuai** [WangJunZzz/abp-vnext-pro#35]
没有装mysql，只有sql server，怎么改？

**Comment by WangJunZzz** [comment]
## 切换MSSQL

1、更改Lion.AbpPro.HttpApi.Host中appsetting 中 “ConnectionStrings“ 的Default字符串

2、更改Lion.AbpPro.IdentityServer中appsetting 中 “ConnectionStrings“ 的Default字符串

3、更改Lion.AbpPro.DbMigrator 中appsetting 中 “ConnectionStrings“ 的Default字符串

4、将Lion.AbpPro.EntityFrameworkCore 中的Volo.Abp.EntityFrameworkCore.MySql NuGet包改为Volo.Abp.EntityFrameworkCore.SqlServer

更改方式如下： AbpProDbContextFactory

将代码块：

```c#
 public AbpProDbContext CreateDbContext(string[] args)
        {
            AbpProEfCoreEntityExtensionMappings.Configure();

            var configuration = BuildConfiguration();

            var builder = new DbContextOptionsBuilder<AbpProDbContext>()
                .UseMySql(configuration.GetConnectionString("Default"), MySqlServerVersion.LatestSupportedServerVersion);

            return new AbpProDbContext(builder.Options);
        }

```

更改为：

```C#
 public AbpProDbContext CreateDbContext(string[] args)
        {
            AbpProEfCoreEntityExtensionMappings.Configure();

            var configuration = BuildConfiguration();

            var builder = new DbContextOptionsBuilder<AbpProDbContext>()
                .UseMySql(configuration.GetConnectionString("Default"), MySqlServerVersion.LatestSupportedServerVersion);

            return new AbpProDbContext(builder.Options);
        }

```

5、更改Lion.AbpPro.HttpApi.Host 下的Hangfire.MySqlStorage NuGet包为Hangfire.SqlServer 并更改因他引起的错误如下：更改AbpProHttpApiHostModule.cs 中的引用；


6、更改 Lion.AbpPro.CAP 项目下的DotNetCore.CAP.MySql NuGet包为DotNetCore.CAP.SqlServer


7、通过命令Remove-Migration 删除项目中Migrations 下由MySql生成的文件

8、删除EntityFrameworkCore层下Migrations文件夹

9、在EntityFrameworkCore目录下重新生产迁移文件:dotnet ef migrations add Init

10、运行 Lion.AbpPro.DbMigrator初始化数据

11、如果要使用通知模块：修改DapperNotificationRepository下的sql=为ms sql格式

**Comment by luchaoshuai** [comment]
漏项不少，改了半天了还是没有成功。
切换个数据库要改的地方也太多了，我还是弄官方的abp去吧。

**Comment by WangJunZzz** [comment]
呃呃，官方的切数据库也是这样的。。。。

**Comment by Ellioti2** [comment]
做到步骤4 下载并安装完 Volo.Abp.EntityFrameworkCore.SqlServer后报错：
Could not find a part of the path 'C:\Users\Administrator\.nuget\packages\lion.abppro.datadictionarymanagement.application.contracts\7.3.3.4\src\Lion.AbpPro.DataDictionaryManagement.Application.Contracts\obj\Release\net7.0\Lion.AbpPro.DataDictionaryManagement.Application.Contracts.GlobalUsings.g.cs'.
