### ISSUE TITLE
vben271 vite启动报 Failed to load source map 错误

### ISSUE THREAD

**Issue by yixiangling** [WangJunZzz/abp-vnext-pro#38]
vben271前端项目启动报错。
Failed to load source map for /node_modules/.vite/@zxcvbn-ts_core.js

npm run serve
`> vben-admin@2.7.1 serve
> npm run dev

> vben-admin@2.7.1 dev
> vite

warn - 'lightBlue' has been renamed to 'sky'.
warn - Please update your color palette to eliminate this warning.
Pre-bundling dependencies:
  vue
  ant-design-vue
  pinia
  vue-router
  vue-i18n
  (...and 34 more)
(this will be run only when your dependencies or config have changed)

  vite v2.6.14 dev server running at:

  > Network:  http://192.168.2.3:4200/
  > Local:    http://localhost:4200/

  ready in 19441ms.

12:02:41 [vite] new dependencies found: qrcode, updating...
12:02:42 [vite] Failed to load source map for /node_modules/.vite/@zxcvbn-ts_core.js?v=538e42a6.
12:02:56 [vite] ✨ dependencies updated, reloading page...`

启动后尝试更改package.json后此错误消失。
此错误只在工程首次启动时发生（vite缓存建立后不再出现），后续启动则不报错。
暂未找到问题根源，只有绕过此问题的办法。

**Comment by WangJunZzz** [comment]
试试 yarn？

**Comment by yixiangling** [comment]
切换npm源安装报错，是采用yarn方式安装相关包组件，上述错误是在所有包安装成功后进行启动时出现的。

**Comment by yixiangling** [comment]
@WangJunZzz 经过多次验证，在同一电脑其它目录克隆工程后重复上述步骤无法重现此问题（未对vite进行任何重置）。
