### ISSUE TITLE
does not work ,HttpApi.Host refuse vue app connection for login 

### ISSUE THREAD

**Issue by mrs01dev** [WangJunZzz/abp-vnext-pro#4]
when vue app try to login
http://localhost:50000/api/app/login 
HttpApi.Host does not respond.
Also:
appsettings.json in  HttpApi.Host have the following entries 
AuthServer": {
    "Authority": "https://localhost:44363",
    "RequireHttpsMetadata": "false"
  },
  "Jwt": {
    "Audience": "http://localhost:5010", //¿Í»§¶Ë±êÊ¶
    "SecurityKey": "dzehzRz9a8asdfasfdadfasdfasdfafsdadfasbasdf=",
    "Issuer": "WangJun", //Ç©·¢Õß
    "ExpirationTime": 2 //¹ýÆÚÊ±¼ä hour
  }

What are the projects running services ["https://localhost:44363" ,"http://localhost:5010"]

Also:
in vue app ,.env.development have entry
VUE_APP_AUTH_URL=http://sts.vnext.identity.development.yhglobal.cn

How to run the projects locally without any external service ?
![image](https://user-images.githubusercontent.com/64358630/115750035-96561d00-a34c-11eb-9e5e-509e5cedb2dd.png)

**Comment by WangJunZzz** [comment]
Clone again
