### ISSUE TITLE
有计划使用Yarp.ReverseProxy替代Ocelot吗？

### ISSUE THREAD

**Issue by sanmen359** [WangJunZzz/abp-vnext-pro#40]
我看到abp官方像是使用Yarp.ReverseProxy而不是Ocelot。
请问有计划使用Yarp.ReverseProxy替代Ocelot吗？
https://github.com/abpframework/eShopOnAbp

**Comment by WangJunZzz** [comment]
这个我了解一下，也可以使用apixis
