### ISSUE TITLE
请教开发最佳实践的方式

### ISSUE THREAD

**Issue by seamusic** [WangJunZzz/abp-vnext-pro#72]
目前这套框架集成了不少好东西。
如果我需要在这个框架基础之上开发自己的业务，应该如何处理才是最佳的实践？
这样可以把自己的业务功能集中在自己的模块下面，同时能够在基础的框架升级的时候及时的去跟进。
另外，如果业务拆分成不同的子模块，那模块与模块之间的调用，应该是如何更好的体现呢？

**Comment by HillCat** [comment]
最好的实践就是去公司上班，拿着老板的钱去实践。

**Comment by WangJunZzz** [comment]
1.如果希望可以更好的升级可以采用最基础的版本(abp-vnext-pro-basic-no-ocelot)
lion.abp new abp-vnext-pro-basic-no-ocelot -c 公司名称 -p 项目名称 -v 版本(可选) -o 项目输出路径(可选).
2.把业务模块单独实现在集成进来时比较好的方式。
