### ISSUE TITLE
之后有考虑做一个模块生成模版么？

### ISSUE THREAD

**Issue by ClementJob** [WangJunZzz/abp-vnext-pro#78]
因为和abp官方的生成有差异

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/204416319-adfa01cd-8bf1-4c4c-a754-a9cd28270e0a.png)
通过cli可以创建模板， 和官方是一样的。
