### ISSUE TITLE
是否支持国产数据库？例如达梦

### ISSUE THREAD

**Issue by itchangc** [WangJunZzz/abp-vnext-pro#82]
是否支持国产数据库？例如达梦

**Comment by WangJunZzz** [comment]
只要有达梦的EF驱动实现就支持。

**Comment by itchangc** [comment]
我明天把ef core 达梦的驱动实现 打包发给你



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月19日 22:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [WangJunZzz/abp-vnext-pro] 是否支持国产数据库？例如达梦 (Issue #82) |

只要有达梦的EF驱动实现就支持。

**Comment by WangJunZzz** [comment]
ok
