### ISSUE TITLE
自动API不可用了吗？

### ISSUE THREAD

**Issue by Xzuner** [WangJunZzz/abp-vnext-pro#84]
感谢作者提供的完整框架，对于快速搭建项目非常有帮助。
使用中发现根据ABP官方文档设置的ABP默认的自动API扫描不生效，需要手写Controller，这个是有什么特殊的设置吗？

**Comment by WangJunZzz** [comment]
由于某些接口不适用，获取对前端代码的生成不支持，所以关闭次功能。
https://github.com/WangJunZzz/abp-vnext-pro/issues/21
