### ISSUE TITLE
Swagger无法映射复杂类型参数

### ISSUE THREAD

**Issue by qiuyuhz** [WangJunZzz/abp-vnext-pro#87]
public Task GetLittleMsg(Guid id, byte[] stream, string content)
    {
        throw new NotImplementedException();
    }
比如stream参数直接被忽略掉了.

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/216540400-b84660f0-e300-4719-b860-00cdee416af4.png)

**Comment by qiuyuhz** [comment]
3Q
