### ISSUE TITLE
是否有计划集成配置中心？

### ISSUE THREAD

**Issue by checkmateTowindn** [WangJunZzz/abp-vnext-pro#88]
多模块或者微服务下，配置总是麻烦的，是否有计划集成配置中心呢？

**Comment by WangJunZzz** [comment]
Nacos or  Apollo？

**Comment by checkmateTowindn** [comment]
Apollo

**Comment by WangJunZzz** [comment]
官网集成文档：https://www.apolloconfig.com/#/zh/usage/dotnet-sdk-user-guide
