### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by xiaochong44** [WangJunZzz/abp-vnext-pro#9]
这个项目非常好，和我用的前后端都完全一样，哈哈。
在项目应用中有点小建议，像identity和tenant模块，用户、角色、租户都要大量增加字段，用实体扩展的方式非常不友好。我在开发中是直接把这里模块的源码加进来，直接改源码非常快，也符合开发的逻辑。
授权和菜单最好改成主流系统的菜单配置模块，可以配置菜单的层级图标等信息。
还有本地化改成数据库形式，管理员可修改翻译

**Comment by WangJunZzz** [comment]
直接把源码加进来，看看后面是否有更多的人有需求。
菜单和授权你那边实现了这个配置吗？
本地化这里会要修改的。

**Comment by xiaochong44** [comment]
有实现了，我的项目不是微服务的形式，直接写在主项目里的

**Comment by WangJunZzz** [comment]
可以参考一下？获取发起pull request 一起参与。

**Comment by xiaochong44** [comment]
没问题，抽时间我整理整理

**Comment by WangJunZzz** [comment]
Nice
