### ISSUE TITLE
tenants/page页面打开不

### ISSUE THREAD

**Issue by ayafl** [WangJunZzz/abp-vnext-pro#93]
![image](https://github.com/WangJunZzz/abp-vnext-pro/assets/22810022/0d35a260-7551-4d92-a358-5a1ecf43e9ea)

**Comment by ayafl** [comment]
![image](https://github.com/WangJunZzz/abp-vnext-pro/assets/22810022/6136581c-4708-42f6-b57d-41c0a3b2e517)
创建租户，但是提示FlagIcon这字段不能为空，到数据库的租户表看了，没有这个字段。麻烦老大看看

**Comment by WangJunZzz** [comment]
已修复,提交记录： https://github.com/WangJunZzz/abp-vnext-pro/commit/43da750979d7a1a4b0e47bffa46d4f72a3931ce1
